const branName = [
    'Abrams',
    'ACC Art Books',
    'Acca Kappa',
    'adidas Originals',
    'Book Publishers',
    'BRANDSHOP',
    'Bronze 56k',
    'Bubble Gum',
    'Burberry',
    'Burlington',
    'Butter Goods',
    'C.P. Company',
    'Call Me 917',
    'Calvin Klein Jeans',
    'Calvin Klein Underwear',
    'Diadora',
    'Diadora Heritage',
    'Dickies',
    'Dime',
    'Dr. Martens',
    'Edwin',
    'Elmer',
    'Enterprise Japan Скоро',
    'Etudes',
    'Evisu',
    'F.C. Real Bristol',
    'Falke',
    'G-Shock',
    'Golden Goose',
    'Gramicci',
    'Grown Alchemist',
    'Hackett',
    'Helly Hansen',
    'Jason Markk',
    'Jordan',
    'K-SWISS',
    'K-Way',
    'Kangol',
    'Lacoste',
    'Lacoste Underwear',
    'LEBON',
    'MA.Strum',
    'maharishi',
    'Maison Kitsune',
    'Maison Margiela',
    'Maison Margiela MM6',
    'Malin+GoetzNapapijri',
    'Native Union',
    'New Balance',
    'NikeOakley',
    'Oliver Peoples',
    'OswenPeaceful Hooligan',
    'Pendleton',
    'Persol',
    'PhaidonREPRESENT',
    'Rick Owens DRKSHDW',
    'RIPNDIP',
    'RizzoliSandqvist',
    'Saucony',
    'Schiffer',
    'SeikoTASCHEN',
    'teNeues',
    'Thames & Hudson',
    'The North Face',
    'thisisneverthat',
    'Umbro',
    'UNAFFECTED',
    'Uniform Bridge',
    'uniform experimentValobra',
    'Vans',
    'Weekend Offender',
    'WoolrichY-3',
    'YEEZYZCWO',
    'Zespa'
];
export default branName